### ISSUE TITLE
errors from go get

### ISSUE THREAD

**Issue by kmulvey** [barnex/cuda5#1]
when running the example here:
https://hpcugent.github.io/easybuild/files/FOSDEM14/FOSDEM14_HPC_devroom_14_GoCUDA.pdf

```
(master)> go get && go build
# github.com/barnex/cuda5/cu
../../barnex/cuda5/cu/context.go:5:18: fatal error: cuda.h: No such file or directory
 //#include <cuda.h>
                  ^
compilation terminated.
```

**Comment by kmulvey** [comment]
ive made some progress but im still not there, i installed cuda dev kit: cuda-6.5-14.x86_64

i changed my code to call cu.Init(0), but now its saying there is no device.  I checked the nvidia getting started guide and verified my card cuda capable:  
```
lspci | grep -i nvidia
01:00.0 VGA compatible controller: NVIDIA Corporation GM107 [GeForce GTX 750] (rev a2)
01:00.1 Audio device: NVIDIA Corporation Device 0fbc (rev a1)
```

error
```
panic: CUDA_ERROR_NO_DEVICE

goroutine 1 [running]:
github.com/barnex/cuda5/cu.Init(0x0)
	/home/kmulvey/go/src/github.com/barnex/cuda5/cu/init.go:14 +0x6a
main.main()
	/home/kmulvey/go/src/github.com/kmulvey/scratch/main.go:10 +0x32

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1
```

my code:

```
package main

import (
	"fmt"

	"github.com/barnex/cuda5/cu"
)

func main() {
	cu.Init(0)
	fmt.Println("Hello, your GPU is:", cu.Device(0).Name())
	fmt.Println("Hello, your GPU is:", cu.Device(0).Properties())
}
```

**Comment by barnex** [comment]
CUDA_ERROR_NO_DEVICE is usually caused by an improper driver. Instead
of lspci, you should nvidia-smi.
